Don't use Netty event loop group directly in Future adpater - fixes  #6
Sammers21/vertx-cassandra-client pull request #8
Opened 2018-05-17 07:44 UTC by Sammers21

2018-05-17 08:02 UTC, tsegismont requested changes
This won't work if we share the client among verticles. You shouldn't get the context when the instance is created, but rather capture it whenever a method is called. I think the utility class (static methods) was fine for an adapter BTW

2018-05-17 08:20 UTC, Sammers21 commented
@tsegismont, just done, can you review?

2018-05-17 08:38 UTC, tsegismont commented on src/main/java/io/vertx/cassandra/impl/Util.java
> +    }, command -> vertx.getOrCreateContext().runOnContext(v -> command.run()));
You can't capture the context here, because you're on a Cassandra driver I/O thread. Invoke `getOrCreateContext` at the top of the method body.

2018-05-18 08:21 UTC, Sammers21 commented on src/main/java/io/vertx/cassandra/impl/Util.java
> +    }, command -> vertx.getOrCreateContext().runOnContext(v -> command.run()));
Got it. Done

2018-05-18 08:27 UTC, Sammers21 commented
@tsegismont , can you review?

2018-05-18 12:44 UTC, tsegismont approved these changes

2018-05-18 12:44 UTC, tsegismont commented
LGTM :+1:

2018-05-18 12:45 UTC, merged